### ISSUE TITLE
Test code under Windows

### ISSUE THREAD

**Issue by cabouman** [cabouman/cython_sandbox#13]
We need to make sure setup.py works for different OS versions.

**Comment by DamonLee5** [comment]
Soumendu suggested that we can do this with Travis. It seems to be very easy to test code under different platforms and compilers in Travis. 
https://docs.travis-ci.com/user/languages/c/

**Comment by cabouman** [comment]
OK, good. This is a perfect case to get some experience with Travis. Please set up a branch to develop and test this implementation. Once I approve it, then we can integrate it into the main branch.

**Comment by cabouman** [comment]
Just tested it under linux. It works fine.

Maybe someone can test under Windows?

**Comment by sjkisner** [comment]
I haven't been able to build in Windows 10 with Mingw64/gcc v10.2.0.  I get an error at the step
    building 'cython_sandbox.wrapped' extension
    error: Microsoft Visual C++ 14.0 or greater is required

**Comment by sjkisner** [comment]
What about icc on linux? Has anybody gotten that to work?  For me it seems to build OK but it fails when running with this error:
cpython-38-x86_64-linux-gnu.so: undefined symbol: __intel_sse2_strchr

**Comment by DamonLee5** [comment]
> What about icc on linux? Has anybody gotten that to work? For me it seems to build OK but it fails when running with this error:
> cpython-38-x86_64-linux-gnu.so: undefined symbol: __intel_sse2_strchr

I think icc need different cflag and lib to compile and link.

**Comment by cabouman** [comment]
If you figure this out, can you add an option in the setup.py file? It should start with the conditional:

`if (os.environ.get('CC') == 'icc') and (os.environ.get('OMPCOMP') !='1'):`

**Comment by DamonLee5** [comment]
> What about icc on linux? Has anybody gotten that to work? For me it seems to build OK but it fails when running with this error:
> cpython-38-x86_64-linux-gnu.so: undefined symbol: __intel_sse2_strchr

Jordan,

I added support to icc. Also, I updated my readme. You can go to my branch and follow the readme to compile and link with icc.
I run it successfully in my cluster with icc. You can try my branch on your machine.

The main idea is that, for ``icc``, we need specific  cflags and a special environment variable ``LDSHARED``. More information can be found in the follwing link.
https://software.intel.com/content/www/us/en/develop/articles/thread-parallelism-in-cython.html

**Comment by cabouman** [comment]
Wenrui, can you do a merge requests to merge your integration of ``icc`` into the main branch?
Make sure you start with a clean version of the current main branch, and add the new features, so you don't add a bunch of junk.

Also, can you point me to somewhere were I can get an educational version of ``icc`` for my mac?

**Comment by DamonLee5** [comment]
> Wenrui, can you do a merge requests to merge your integration of `icc` into the main branch?
> Make sure you start with a clean version of the current main branch, and add the new features, so you don't add a bunch of junk.
> 
> Also, can you point me to somewhere were I can get an educational version of `icc` for my mac?

The `icc` of my mac is expired, I tested the `icc` compiler in the cluster. 
I found a webpage here, however, I did not find an educational version of `icc`.
https://software.intel.com/content/www/us/en/develop/documentation/get-started-with-cpp-compiler-for-macos/top.html

**Comment by sjkisner** [comment]
Still unable to get this to compile with MinGW/gcc under Windows. Cython looks for a Visual Studio C++ compiler by default. Supposedly the setting can be overrided by creating a distutils.cfg file in the python source but it's not working in my case. See [this](https://cython.readthedocs.io/en/latest/src/tutorial/appendix.html) and [this](https://wiki.python.org/moin/WindowsCompilers)
